project_name: sshh

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: .
    binary: sshh
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
    - title: Others
      order: 999

release:
  github:
    owner: astro
    name: sshh
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

nfpms:
  - id: sshh
    package_name: sshh
    homepage: https://github.com/astro/sshh
    description: Secure SSH credential manager & connector
    maintainer: Astro
    license: MIT
    formats:
      - deb
      - rpm
